const tweet = { created_at: 'Thu Nov 03 04:22:39 +0000 2016',
  id: 794032014487932900,
  id_str: '794032014487932928',
  text: '@DavidCayJ Trump will not release his taxes. That means what is still hidden is certainly worse than anything disco… https://t.co/NsqaLNjrUO',
  display_text_range: [ 11, 140 ],
  source: '<a href="http://twitter.com/#!/download/ipad" rel="nofollow">Twitter for iPad</a>',
  truncated: true,
  in_reply_to_status_id: 794031532658851800,
  in_reply_to_status_id_str: '794031532658851840',
  in_reply_to_user_id: 338608917,
  in_reply_to_user_id_str: '338608917',
  in_reply_to_screen_name: 'DavidCayJ',
  user:
   { id: 484449533,
     id_str: '484449533',
     name: 'dgmtick1',
     screen_name: 'dgmtick1',
     location: null,
     url: null,
     description: null,
     protected: false,
     verified: false,
     followers_count: 13,
     friends_count: 121,
     listed_count: 0,
     favourites_count: 954,
     statuses_count: 1309,
     created_at: 'Mon Feb 06 03:48:28 +0000 2012',
     utc_offset: -25200,
     time_zone: 'Pacific Time (US & Canada)',
     geo_enabled: false,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_link_color: '0084B4',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_1_normal.png',
     profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_1_normal.png',
     default_profile: true,
     default_profile_image: true,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  extended_tweet:
   { full_text: '@DavidCayJ Trump will not release his taxes. That means what is still hidden is certainly worse than anything discovered to date. Criminal perhaps',
     display_text_range: [ 11, 146 ],
     entities: { hashtags: [], urls: [], user_mentions: [Object], symbols: [] } },
  retweet_count: 0,
  favorite_count: 0,
  entities:
   { hashtags: [],
     urls: [ [Object] ],
     user_mentions: [ [Object] ],
     symbols: [] },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1478146959312' };