twitter:
  build: ./twitter
  volumes:
    - "./twitter:/src/twitter"
  command: "nodemon -L twitter/app"

client:
  build: ./client
  volumes:
    - "./client:/src/client"
  ports:
    - "80:3000"
  command: "nodemon -L client/bin/www"